### ISSUE TITLE
Lv.1 질문사항

### ISSUE THREAD

**Issue by mottoslo** [mottoslo/h99-Spring-Assignments#1]
1. DeleteRequestDto의 @NoArgsContructor 관련
   클라이언트의 삭제요청의 Body를 DeleteRequestDto로 받아오는 과정에서, JSON이 객체로 파싱되지 않는 오류가 발생했습니다.
   좀 찾아보니 JSON을 객체로 파싱해주는 라이브러리에서, 받아줄 객체의 기본 생성자가 없으면 파싱이 안된다고 하여 
   @NoArgsContructor를 달아 해결했는데요, PUT요청의 Body를 받아오는 ArticleRequestDto에는 @NoArgsConstructor 애노테이션
   없이도 JSON을 객체로 받아오는데 문제가 생기지 않습니다. 두 개의 차이가 어떻게 발생하는지 모르겠습니다.

2. 
![image](https://user-images.githubusercontent.com/57926597/232705209-d80f0e22-f895-4867-83e8-e3d91c50b6df.png)
위와 같이 DTO객체의 필드값이 final이 될 수 있다는 경고가 많이 뜨는데, 이를 final로 만들어 주어도 무방한지 궁금합니다.
(이 과제에서 DTO는 Service에 데이터를 전달하여 Article 객체를 생성하거나, 처리 완료된 데이터를 클라이언트에 전달할 때만 사용되므로 final로 선언해도 괜찮을 것 같기는 하지만, 다른 경우가 있을까 하여 질문드립니다.)

**Comment by iamzin** [comment]
멘토링 시간에 답변드렸던 내용이네요.  :)
복습 겸 답변을 직접 남겨보시면 좋을 것 같습니다.
