### ISSUE TITLE
Lv2 과제 궁금증 -> 주말에 해보기

### ISSUE THREAD

**Issue by mottoslo** [mottoslo/h99-Spring-Assignments#4]
Article 엔티티와 Users 엔티티 연관관계를 지어줬는데,

Article을 하나 검색해올 때 Users객체를 거기에 포함해서 가져오게 된다.

Article의 필드로 username을 가지고 있는거랑 비교해서 어떤게 효율적인지 ?

**Comment by iamzin** [comment]
연관관계를 맺는 기준을 찾아보시면 좋을 것 같습니다.
일반적으로 연관관계는 라이프 사이클이 같은 객체 간에 맺습니다.
