### ISSUE TITLE
Spring Security redirection때문에 헤더에 토큰을 담을 수가 없음 

### ISSUE THREAD

**Issue by mottoslo** [mottoslo/h99-Spring-Assignments#6]
로그인 시 Successhandler의 onAuthenticationSuccess를 오버라이드하여 jwt토큰을 담았으나, Spring의 기본 핸들러가 처리해주는 로깅 기능, 로그인 실패 횟수 관리, 리디렉션 등의 기능을 그대로 사용하고싶어 오버라이드 한 메소드 내에서 기본 핸들러를 다시 호출해주었습니다. 그러나 리디렉션 시에 HTTP 요청의 response가 초기화되어 헤더에 담았던 jwt 토큰이 클라이언트에게 전달되지 않고 있스ㅏㅓㅑ다    

```java

    @Override
    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException, ServletException {
        String token = jwtUtil.createToken(authentication.getName());
        response.addHeader(JwtUtil.AUTHORIZATION_HEADER, token);
//        System.out.println(response.isCommitted());
//        defaultHandler.onAuthenticationSuccess(request, response, authentication);  // 리디렉션 어케 처리할건지


    }
```

**Comment by iamzin** [comment]
일반적으로 단일 Spring App이 아니라, Frontend가 존재하면 위와 같은 Handling이 불필요할 것 같습니다.
불가피하게 필요하다면, redirecting은 Frontend에서 처리해주는게 적절해보입니다.

**Comment by mottoslo** [comment]
<정리>
리다이렉션 등을 처리해주는 Spring Security의 기본 successhandler를 사용하고자 하여 custom handler의 마지막에 default successhandler를 호출하여 발생한 문제였으나, 서버에서 리다이렉션을 처리해줄 필요가 없다면 custom successhandler에서 끝을 내므로 문제x

추가 : 굳이 지금과 같이 구현해야한다면 리다이렉션 전의 Httpresponse의 status를 307(Temporary redirect)로 set 해주어 기존 header를 가지고 갈 수 있다.
