### ISSUE TITLE
예외 케이스 처리를 보통 얼마나 꼼꼼하게 하는지 궁금합니다

### ISSUE THREAD

**Issue by mottoslo** [mottoslo/h99-Spring-Assignments#7]
발생할 수 있는 Exception 처리를 꼼꼼하게 해주는 건 당연하겠지만,
정상적인 상황이면 발생할 수 없는 상황에 대한 예외처리도 해주어야하는지 궁금합니다.

간단하게 예를 들면,
id = 5인 댓글에 대한 삭제 요청이 있을 때 이를 DB에서 삭제하지 않고 isDeleted라는 flag로 관리한다고 했을 때,
정상적인 상황이라면 게시판에서 id = 5인 댓글은 삭제된 댓글입니다 라고 표시되고 대댓글 달기 버튼이 없을 것입니다.
따라서 id = 5인 댓글에 대한 대댓글 요청은 서버에 전달되지 않아야 하는데, 혹시 모르는 경우에 대비해 CommentService
에서 대댓글을 달고자 하는 댓글이 삭제된 댓글인지를 확인하는 검증이 필요할까요 ?

불필요한 코드가 많아져 그렇게 하고싶지 않은데, 강의에서 강사님이 비슷한 경우에 "이런 경우는 원래 있으면 안되지만 혹시 모르니까 처리를 해주도록 하겠습니다" 라고 말씀하신 적이 있어 질문드립니다.

그냥 개인의 스타일 차이인지, 아니면 보통 "혹시 모르니까를" 생각해서 처리를 해주는지 궁금합니다

**Comment by mottoslo** [comment]
생각해보니까 버튼이 없다고 해도 Postman으로도 요청을 밀어넣을 수 있으니까 처리를 해주는게 맞는 것 같기도 합니다 ..

**Comment by iamzin** [comment]
예를 들어 페이지를 2개 띄워놓고 한 쪽에서만 지웠을 때, 다른 페이지에서는 대댓글을 달 수 있는 버튼이 아직 존재할 것 입니다.
이러한 경우를 대비하여 방어적으로 개발하는 것이 좋아보입니다.

별개로 말씀하신 postman을 통한 요청은 security side에서 cors로 api 요청 자체가 불가해야하는게 맞는 것 같습니다.

**Comment by mottoslo** [comment]
감사합니다 !
